#!/bin/bash

killall swayidle

swayidle -w \
    timeout 300 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    timeout 320 'swaylock -f' \
    timeout 600 'systemctl suspend' \
    before-sleep 'swaylock -f' \
&
