#!/bin/sh

case "$1" in
    lock)
        swaylock
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
        systemctl suspend && swaylock
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0
