#!/usr/bin/env bash

cd "$(dirname "$0")"
exec sudo nixos-rebuild \
	$@ \
	--flake $(dirname "$0")#$(hostname)

# i.e
# --upgrade
# sudo nixos-rebuild switch --flake /home/sean/.dotfiles#nixos-notebook
# sudo nixos-rebuild switch -I nixos-config=/home/sean/.dotfiles/hosts/nixos-wsl/configuration.nix
