# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # unlock optional LUKS devices (legacy drives)
  environment.etc."crypttab".text = ''
    cryptroot    /dev/disk/by-uuid/f8c3d579-fea9-4be5-a69b-4cb7352b8b23   /root/keyfile     luks
  '';

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/b54eb7f9-fc23-4229-b7c6-483cb31fc556";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/A9E1-71D1";
      fsType = "vfat";
    };

    "/media/store" = {
      device = "/dev/disk/by-uuid/c23ef302-4d21-4a4a-b5e8-cb7af12ef0ec";
      options = ["nofail"];
      fsType = "ext4";
    };

    "/media/games" = {
      device = "/dev/disk/by-uuid/eef1d983-1deb-45f4-9288-8353e37207b0";
      options = ["nofail"];
      fsType = "ext4";
    };

    "/mnt/oldroot" = {
      device = "/dev/disk/by-uuid/f8e426b3-e661-4ac5-b61b-90ec1c31e332";
      options = ["ssd" "noatime" "nofail"];
      fsType = "btrfs";
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp38s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
